#ifndef AWP_CONSTANTS_H
#define AWP_CONSTANTS_H

#define AWP_REDUE_SEARCH_INTERVAL 4
#define AWP_MAX_BLOCKS_ON_LINE 10
#define AWP_FRAME_BYTE_LENGTH 13
#define AWP_ADDR_LENGTH 64
#define AWP_ADDR_BYTE_LENGTH (AWP_ADDR_LENGTH / 8)

#endif // AWP_CONSTANTS_H